// Golden parity: the TS reimplementations must match the Python originals
// byte-for-byte over the committed fixtures (generated by
// web/oracle/scripts/gen_golden.py). Regenerating the goldens is the ONLY
// sanctioned way to change TS scoring behaviour (see web/docs/DECISIONS.md).

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { alignPhonemes, comparePhonemes, levenshtein } from '../src/domain/practiceFunctions.js';
import { isTolerated } from '../src/domain/foldMap.js';

interface ComparisonCase {
  user: string;
  correct: string;
  levenshtein: number;
  exact: boolean;
  similarity: number;
  distance: number;
  ops: { op: string; target: string; user: string }[];
}

interface FoldmapCheck {
  lang: string;
  a: string;
  b: string;
  tolerated: boolean;
}

function golden<T>(name: string): T {
  const path = fileURLToPath(new URL(`./golden/${name}`, import.meta.url));
  return JSON.parse(readFileSync(path, 'utf-8')) as T;
}

describe('golden parity with Python scoring (comparison.py)', () => {
  const { cases } = golden<{ cases: ComparisonCase[] }>('comparison.json');

  it('levenshtein matches on every case', () => {
    for (const c of cases) {
      expect(levenshtein(c.user, c.correct), `${c.user} vs ${c.correct}`).toBe(c.levenshtein);
    }
  });

  it('comparePhonemes exact/similarity/distance match on every case', () => {
    for (const c of cases) {
      const s = comparePhonemes(c.user, c.correct);
      expect(s.exactMatch, `${c.user} exact`).toBe(c.exact);
      expect(s.distance, `${c.user} distance`).toBe(c.distance);
      expect(s.similarity, `${c.user} similarity`).toBeCloseTo(c.similarity, 12);
    }
  });

  it('alignPhonemes reproduces get_edit_operations (target-oriented)', () => {
    // Python kind 'substitute' == TS 'sub'; both sides target-oriented.
    const kind = (op: string): string => (op === 'substitute' ? 'sub' : op === 'insert' ? 'ins' : op === 'delete' ? 'del' : 'equal');
    for (const c of cases) {
      const segs = alignPhonemes(c.user, c.correct);
      expect(
        segs.map((s) => ({ op: s.op, target: s.target, user: s.user })),
        `${c.user} vs ${c.correct}`,
      ).toEqual(c.ops.map((o) => ({ op: kind(o.op), target: o.target, user: o.user })));
    }
  });
});

describe('golden parity with Python fold_map.py', () => {
  const { checks } = golden<{ checks: FoldmapCheck[] }>('foldmap.json');

  it('isTolerated matches on every recorded check', () => {
    for (const c of checks) {
      expect(isTolerated(c.lang, c.a, c.b), `${c.lang}: ${c.a}~${c.b}`).toBe(c.tolerated);
      expect(isTolerated(c.lang, c.b, c.a), `${c.lang}: ${c.b}~${c.a}`).toBe(c.tolerated);
    }
  });
});
