#!/usr/bin/env python3
"""
Fit the vowel detector's per-vowel Gaussians (data/calibration/vowel.yaml) on DEV tokens.

    venv/bin/python scripts/realised_phone/calibrate_vowel.py \\
        --tokens fr=/opt/cpdata/fr/dev/list.tsv:y,u,i --tokens en=/opt/cpdata/en/dev/list.tsv:ʉː=ʉ,ʉ \\
        --cache /opt/align_cache --out src/realised_phone/data/calibration/vowel.yaml

Each --tokens is LANG=TSV:PHONES, PHONES a comma list of aligner labels, optionally
renamed with '=' (ʉː=ʉ pools English long [ʉː] into the [ʉ] model). Codas are kept.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

import numpy as np  # noqa: E402
import yaml  # noqa: E402

from realised_phone import corpora  # noqa: E402
from realised_phone.detectors.vowel import FEATURES, VowelDetector  # noqa: E402
from realised_phone.tokens import rhotic_tokens  # noqa: E402

ALIGNERS = {"fr": ("french_mfa", "french_mfa"), "en": ("english_mfa", "english_us_mfa"),
            "es": ("spanish_mfa", "spanish_mfa"), "nl": ("dutch_cv", "dutch_cv")}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tokens", action="append", required=True)
    ap.add_argument("--cache")
    ap.add_argument("--jobs", type=int, default=4)
    ap.add_argument("--min-sd", type=float, default=0.03)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    det = VowelDetector({"models": {}})
    feats = defaultdict(list)
    sources = {}
    for spec in args.tokens:
        lang, rest = spec.split("=", 1)
        tsv, phones = rest.rsplit(":", 1)
        label_of = {}
        for p in phones.split(","):
            src, _, dst = p.partition("=")
            label_of[src] = dst or src
        am, dic = ALIGNERS[lang]
        for t in rhotic_tokens(corpora.tsv(tsv), am, dic, label_of, lang, cache_dir=args.cache, jobs=args.jobs):
            m = det.measure(t["x"], t["sr"], (t["phone"].start, t["phone"].end))
            if all(m.get(f) is not None for f in FEATURES):
                feats[t["label"]].append([m[f] for f in FEATURES])
                sources[t["label"]] = f"{lang}: {tsv}"
    models = {}
    for p, rows in feats.items():
        a = np.array(rows)
        models[p] = {"mean": [round(float(v), 4) for v in a.mean(0)],
                     "sd": [round(float(max(v, args.min_sd)), 4) for v in a.std(0)],
                     "n": len(rows), "source": sources[p]}
    cal = {"calibrated": True, "features": list(FEATURES), "max_formant_hz": 5500.0,
           "provenance": {"script": "scripts/realised_phone/calibrate_vowel.py", "date": dt.date.today().isoformat(),
                          "caveat": "each vowel's tokens come from ONE language's speakers/recordings; "
                                    "cross-language contrasts (e.g. French [y] vs English [ʉ]) may partly "
                                    "reflect recording differences"},
           "models": models}
    Path(args.out).write_text("# Vowel detector models -- generated by calibrate_vowel.py; edit there.\n"
                              + yaml.safe_dump(cal, allow_unicode=True, sort_keys=False), encoding="utf-8")
    for p, m in models.items():
        print(p, m["n"], m["mean"], m["sd"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
