"""
espeak-ng allophony fold-map: tolerance lookup for the weighted phone-distance
scorer (beads miolingo-ark -> miolingo-8f0).

The data file ``espeak_fold_map.json`` (same directory) is generated by
``espeak_mine.py`` from the espeak-ng phsource tree + binary. It records,
per language, the empirical IPA inventory and a set of **tolerated substitution
pairs** -- mechanical variants and context-predictable native allophony
(reduction, devoicing, positional realization) that the scorer should treat as
*accent*, not *error* (Tier 1+2 policy).

Tolerance is pairwise and intentionally NOT transitive: ``ɪ~ə`` and ``ɛ~ə`` do
not imply ``ɪ~ɛ``. This module is dependency-free; the panphon weighting that
scores non-tolerated pairs lives in the scorer (miolingo-8f0), which calls
``is_tolerated`` to zero out tolerated substitutions.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_DATA = Path(__file__).resolve().parent / "data" / "espeak_fold_map.json"

# App/voice language codes -> fold-map keys.
_ALIASES = {
    "pt": "pt", "pt-br": "pt", "pt_br": "pt", "br": "pt",
    "pt-pt": "pt-pt", "pt_pt": "pt-pt",
    "fr": "fr", "fr-fr": "fr",
    "nl": "nl", "nl-be": "nl", "flemish": "nl",
    "en": "en", "en-gb": "en", "en-rp": "en", "en-us": "en",
}


@lru_cache(maxsize=1)
def _load() -> dict:
    return json.loads(_DATA.read_text("utf-8"))


def _key(lang: str) -> str:
    k = _ALIASES.get(lang.lower().replace(" ", ""))
    if k is None:
        raise KeyError(f"no fold-map for language {lang!r}; "
                       f"known: {sorted(set(_ALIASES.values()))}")
    return k


def languages() -> list[str]:
    """Fold-map keys actually present in the data file."""
    return [k for k in _load() if not k.startswith("_")]


def inventory(lang: str) -> list[str]:
    """Empirical IPA segment inventory observed for the language."""
    return _load()[_key(lang)]["inventory"]


@lru_cache(maxsize=None)
def tolerated_pairs(lang: str) -> frozenset:
    """Frozenset of ``frozenset({a, b})`` tolerated substitution pairs."""
    data = _load()[_key(lang)]
    return frozenset(frozenset(tp["pair"]) for tp in data["tolerated_pairs"])


def is_tolerated(lang: str, a: str, b: str) -> bool:
    """True if substituting IPA segment ``a`` for ``b`` is accent, not error."""
    if a == b:
        return True
    return frozenset((a, b)) in tolerated_pairs(lang)


def elision_candidates(lang: str) -> list[dict]:
    """IPA segments espeak may delete in context (insertion/deletion discount
    hints for the scorer); not auto-folded."""
    return _load()[_key(lang)]["elision_candidates"]


def meta() -> dict:
    return _load()["_meta"]
